import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "V-Klass Transport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} relative antialiased min-h-screen`}>
        <Navbar />
        {children}
        <Image
          src="/back-2.jpg"
          alt="background pattern"
          fill
          style={{ objectFit: "cover", objectPosition: "center" }}
          className="absolute inset-0 -z-10 pointer-events-none"
          priority
        />
        </body>
      </html>
    );
  }